### ISSUE TITLE
ObjectType 希望能添加支持嵌套

### ISSUE THREAD

**Issue by hiyangguo** [rsuite/rsuite-schema#2]
### One-line summary [问题简述]
希望能为 ObjectType 添加支持嵌套描述的功能，类似于 React 的 [Proptype](https://facebook.github.io/react/docs/typechecking-with-proptypes.html#proptypes)

### Expected behaviour [期望结果]
ObjectType 希望能添加支持嵌套

**Comment by simonguo** [comment]
https://rsuitejs.com/components/schema/
```js
ObjectType().shape({
  email: StringType().isEmail('应该是一个 email'),
  age: NumberType().min(18, '年龄应该大于18岁')
})
```
